[build-system]
requires = ["hatchling", "torch"]
build-backend = "hatchling.build"

[project]
name = "diff_gaussian_rasterization"
version = "0.0.1"
authors = [
    { name = "GRAPHDECO Research Group", email = "george.drettakis@inria.fr" },
]
description = "Differentiable Gaussian Rasterization"
license = { file = "LICENSE.md" }

[tool.hatch.build.targets.wheel.force-include]
"cuda_rasterizer" = "diff_gaussian_rasterization/cuda_rasterizer"
"third_party" = "diff_gaussian_rasterization/third_party"

[tool.hatch.build]
artifacts = [
    "diff_gaussian_rasterization/*.so",
    "diff_gaussian_rasterization/*.pyd",
]

[tool.hatch.build.targets.wheel]
packages = ["diff_gaussian_rasterization"]
