[build-system]
requires = ["hatchling", "torch"]
build-backend = "hatchling.build"

[project]
name = "simple_knn"
version = "0.0.1"
authors = [
    { name = "GRAPHDECO Research Group", email = "george.drettakis@inria.fr" },
]
description = "Simple KNN CUDA Implementation"
license = { file = "LICENSE.md" }

[tool.hatch.build]
artifacts = ["simple_knn/*.so", "simple_knn/*.pyd"]

[tool.hatch.build.targets.wheel]
packages = ["simple_knn"]
