# configs/default.yaml

data:
  path: null
  train_ratio: 0.9
  norm_eps: 1e-8
  num_workers: 4

initialization:
  method: "random"
  num_gaussians: 2841
  opacity_value: 0.171593437558469
  scale_value: 0.11765908010971183

model:
  latent_dim: 32
  attribute_network:
    hidden_dim: 64
    num_layers: 5
    pos_enc_freqs: 64
    dropout_p: 0.0
  contribution_decoder:
    hidden_dim: 64
    num_layers: 2
    dropout_p: 0.1

training:
  iterations: 20000
  batch_size: 32
  stop_xyz_iter_ratio: 0.6475677657947458
  rx_noise_std: 0.00515703009014638
  lambda_activation_l1: 0.08943108740723381
  optimizer:
    eps: 5.367904534706294e-08
    weight_decay: 5.812418520824106e-07
  learning_rate:
    position_init: 0.0029312013434173536
    position_final: 1.5632213138023576e-05
    position_delay_mult: 0.01297675524333455
    rotation: 0.0030094762969635983
    scaling: 0.0070922344826442624
    attribute_net: 0.0013435929472720757
    decoder: 0.0013555615609836757
  snr_eps: 1.0e-10

experiment:
  name: "grf_run"
  seed: 42
  device: "cuda"
  log_dir: "logs"
  log_freq: 30
  eval_freq: 250
  checkpoint_freq: 1500
  tensorboard: true
  log_grad_stats: false

evaluation:
  batch_size: 1
  num_samples: 3
  snr_eps: 1e-10
  unnormalize_samples: false
